# Generated by Django 5.0.7 on 2024-07-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=150)),
                ('rg_ie', models.CharField(max_length=150)),
                ('zip_code', models.TextField(max_length=11)),
                ('address', models.TextField(max_length=150)),
                ('neighborhood', models.TextField(max_length=150)),
                ('number', models.TextField(max_length=5)),
                ('city', models.TextField(max_length=30)),
                ('state', models.TextField(max_length=3)),
                ('ddd', models.TextField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
    ]
