# Generated by Django 5.0.7 on 2024-07-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_clients_deleted_at_alter_clients_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='ddd',
            field=models.TextField(blank=True, max_length=4, null=True),
        ),
    ]
