# Generated by Django 5.0.7 on 2024-08-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_clients_ddd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
