# Generated by Django 5.0.7 on 2024-08-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_clients_deleted_at_alter_clients_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
